//! 系统预设 Provider 配置
//!
//! 定义所有 60+ 系统预设 Provider 的配置，与前端 `SYSTEM_PROVIDERS` 保持一致。
//!
//! **Feature: provider-ui-refactor**
//! **Validates: Requirements 3.1-3.6**

use crate::database::dao::api_key_provider::{ApiKeyProvider, ApiProviderType, ProviderGroup};
use chrono::Utc;

/// 系统 Provider 配置定义
pub struct SystemProviderDef {
    pub id: &'static str,
    pub name: &'static str,
    pub provider_type: ApiProviderType,
    pub api_host: &'static str,
    pub group: ProviderGroup,
    pub sort_order: i32,
    pub api_version: Option<&'static str>,
}

/// 获取所有系统 Provider 配置
pub fn get_system_providers() -> Vec<SystemProviderDef> {
    vec![
        // =========================================================================
        // 主流 AI (10个) - Requirements 3.1
        // =========================================================================
        SystemProviderDef {
            id: "openai",
            name: "OpenAI",
            provider_type: ApiProviderType::OpenaiResponse,
            api_host: "https://api.openai.com",
            group: ProviderGroup::Mainstream,
            sort_order: 1,
            api_version: None,
        },
        SystemProviderDef {
            id: "anthropic",
            name: "Anthropic",
            provider_type: ApiProviderType::Anthropic,
            api_host: "https://api.anthropic.com",
            group: ProviderGroup::Mainstream,
            sort_order: 2,
            api_version: None,
        },
        SystemProviderDef {
            id: "gemini",
            name: "Gemini",
            provider_type: ApiProviderType::Gemini,
            api_host: "https://generativelanguage.googleapis.com",
            group: ProviderGroup::Mainstream,
            sort_order: 3,
            api_version: None,
        },
        SystemProviderDef {
            id: "deepseek",
            name: "DeepSeek",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.deepseek.com",
            group: ProviderGroup::Mainstream,
            sort_order: 4,
            api_version: None,
        },
        SystemProviderDef {
            id: "moonshot",
            name: "Moonshot",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.moonshot.cn",
            group: ProviderGroup::Mainstream,
            sort_order: 5,
            api_version: None,
        },
        SystemProviderDef {
            id: "groq",
            name: "Groq",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.groq.com/openai",
            group: ProviderGroup::Mainstream,
            sort_order: 6,
            api_version: None,
        },
        SystemProviderDef {
            id: "grok",
            name: "Grok (xAI)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.x.ai",
            group: ProviderGroup::Mainstream,
            sort_order: 7,
            api_version: None,
        },
        SystemProviderDef {
            id: "mistral",
            name: "Mistral",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.mistral.ai",
            group: ProviderGroup::Mainstream,
            sort_order: 8,
            api_version: None,
        },
        SystemProviderDef {
            id: "perplexity",
            name: "Perplexity",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.perplexity.ai/",
            group: ProviderGroup::Mainstream,
            sort_order: 9,
            api_version: None,
        },
        SystemProviderDef {
            id: "cohere",
            name: "Cohere",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.cohere.ai",
            group: ProviderGroup::Mainstream,
            sort_order: 10,
            api_version: None,
        },
        // =========================================================================
        // 国内 AI (15个) - Requirements 3.2
        // =========================================================================
        SystemProviderDef {
            id: "zhipu",
            name: "智谱 (ZhiPu)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://open.bigmodel.cn/api/paas/v4/",
            group: ProviderGroup::Chinese,
            sort_order: 11,
            api_version: None,
        },
        SystemProviderDef {
            id: "baichuan",
            name: "百川 (Baichuan)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.baichuan-ai.com",
            group: ProviderGroup::Chinese,
            sort_order: 12,
            api_version: None,
        },
        SystemProviderDef {
            id: "dashscope",
            name: "百炼/通义千问 (Dashscope)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://dashscope.aliyuncs.com/compatible-mode/v1/",
            group: ProviderGroup::Chinese,
            sort_order: 13,
            api_version: None,
        },
        SystemProviderDef {
            id: "stepfun",
            name: "阶跃星辰 (StepFun)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.stepfun.com",
            group: ProviderGroup::Chinese,
            sort_order: 14,
            api_version: None,
        },
        SystemProviderDef {
            id: "doubao",
            name: "豆包 (Doubao)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://ark.cn-beijing.volces.com/api/v3/",
            group: ProviderGroup::Chinese,
            sort_order: 15,
            api_version: None,
        },
        SystemProviderDef {
            id: "minimax",
            name: "MiniMax",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.minimaxi.com/v1",
            group: ProviderGroup::Chinese,
            sort_order: 16,
            api_version: None,
        },
        SystemProviderDef {
            id: "yi",
            name: "零一万物 (Yi)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.lingyiwanwu.com",
            group: ProviderGroup::Chinese,
            sort_order: 17,
            api_version: None,
        },
        SystemProviderDef {
            id: "hunyuan",
            name: "腾讯混元 (Hunyuan)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.hunyuan.cloud.tencent.com",
            group: ProviderGroup::Chinese,
            sort_order: 18,
            api_version: None,
        },
        SystemProviderDef {
            id: "tencent-cloud-ti",
            name: "腾讯云 TI",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.lkeap.cloud.tencent.com",
            group: ProviderGroup::Chinese,
            sort_order: 19,
            api_version: None,
        },
        SystemProviderDef {
            id: "baidu-cloud",
            name: "百度云 (Baidu Cloud)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://qianfan.baidubce.com/v2/",
            group: ProviderGroup::Chinese,
            sort_order: 20,
            api_version: None,
        },
        SystemProviderDef {
            id: "infini",
            name: "无问芯穹 (Infini)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://cloud.infini-ai.com/maas",
            group: ProviderGroup::Chinese,
            sort_order: 21,
            api_version: None,
        },
        SystemProviderDef {
            id: "modelscope",
            name: "魔搭 (ModelScope)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api-inference.modelscope.cn/v1/",
            group: ProviderGroup::Chinese,
            sort_order: 22,
            api_version: None,
        },
        SystemProviderDef {
            id: "xirang",
            name: "息壤 (Xirang)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://wishub-x1.ctyun.cn",
            group: ProviderGroup::Chinese,
            sort_order: 23,
            api_version: None,
        },
        SystemProviderDef {
            id: "mimo",
            name: "小米 MiMo",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.xiaomimimo.com",
            group: ProviderGroup::Chinese,
            sort_order: 24,
            api_version: None,
        },
        SystemProviderDef {
            id: "zhinao",
            name: "360 智脑 (Zhinao)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.360.cn",
            group: ProviderGroup::Chinese,
            sort_order: 25,
            api_version: None,
        },
        // =========================================================================
        // 云服务 (5个) - Requirements 3.3
        // =========================================================================
        SystemProviderDef {
            id: "azure-openai",
            name: "Azure OpenAI",
            provider_type: ApiProviderType::AzureOpenai,
            api_host: "",
            group: ProviderGroup::Cloud,
            sort_order: 26,
            api_version: Some("2024-02-15-preview"),
        },
        SystemProviderDef {
            id: "vertexai",
            name: "VertexAI",
            provider_type: ApiProviderType::Vertexai,
            api_host: "",
            group: ProviderGroup::Cloud,
            sort_order: 27,
            api_version: None,
        },
        SystemProviderDef {
            id: "aws-bedrock",
            name: "AWS Bedrock",
            provider_type: ApiProviderType::AwsBedrock,
            api_host: "",
            group: ProviderGroup::Cloud,
            sort_order: 28,
            api_version: None,
        },
        SystemProviderDef {
            id: "github",
            name: "Github Models",
            provider_type: ApiProviderType::Openai,
            api_host: "https://models.github.ai/inference",
            group: ProviderGroup::Cloud,
            sort_order: 29,
            api_version: None,
        },
        SystemProviderDef {
            id: "copilot",
            name: "Github Copilot",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.githubcopilot.com/",
            group: ProviderGroup::Cloud,
            sort_order: 30,
            api_version: None,
        },
        // =========================================================================
        // API 聚合/中转服务 (25个) - Requirements 3.4
        // =========================================================================
        SystemProviderDef {
            id: "silicon",
            name: "Silicon Flow",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.siliconflow.cn",
            group: ProviderGroup::Aggregator,
            sort_order: 31,
            api_version: None,
        },
        SystemProviderDef {
            id: "openrouter",
            name: "OpenRouter",
            provider_type: ApiProviderType::Openai,
            api_host: "https://openrouter.ai/api/v1/",
            group: ProviderGroup::Aggregator,
            sort_order: 32,
            api_version: None,
        },
        SystemProviderDef {
            id: "aihubmix",
            name: "AiHubMix",
            provider_type: ApiProviderType::Openai,
            api_host: "https://aihubmix.com",
            group: ProviderGroup::Aggregator,
            sort_order: 33,
            api_version: None,
        },
        SystemProviderDef {
            id: "302ai",
            name: "302.AI",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.302.ai",
            group: ProviderGroup::Aggregator,
            sort_order: 34,
            api_version: None,
        },
        SystemProviderDef {
            id: "together",
            name: "Together",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.together.xyz",
            group: ProviderGroup::Aggregator,
            sort_order: 35,
            api_version: None,
        },
        SystemProviderDef {
            id: "fireworks",
            name: "Fireworks",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.fireworks.ai/inference",
            group: ProviderGroup::Aggregator,
            sort_order: 36,
            api_version: None,
        },
        SystemProviderDef {
            id: "nvidia",
            name: "NVIDIA",
            provider_type: ApiProviderType::Openai,
            api_host: "https://integrate.api.nvidia.com",
            group: ProviderGroup::Aggregator,
            sort_order: 37,
            api_version: None,
        },
        SystemProviderDef {
            id: "hyperbolic",
            name: "Hyperbolic",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.hyperbolic.xyz",
            group: ProviderGroup::Aggregator,
            sort_order: 38,
            api_version: None,
        },
        SystemProviderDef {
            id: "cerebras",
            name: "Cerebras",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.cerebras.ai/v1",
            group: ProviderGroup::Aggregator,
            sort_order: 39,
            api_version: None,
        },
        SystemProviderDef {
            id: "ppio",
            name: "PPIO",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.ppinfra.com/v3/openai/",
            group: ProviderGroup::Aggregator,
            sort_order: 40,
            api_version: None,
        },
        SystemProviderDef {
            id: "qiniu",
            name: "七牛 (Qiniu)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.qnaigc.com",
            group: ProviderGroup::Aggregator,
            sort_order: 41,
            api_version: None,
        },
        SystemProviderDef {
            id: "tokenflux",
            name: "TokenFlux",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.tokenflux.ai/openai/v1",
            group: ProviderGroup::Aggregator,
            sort_order: 42,
            api_version: None,
        },
        SystemProviderDef {
            id: "cephalon",
            name: "Cephalon",
            provider_type: ApiProviderType::Openai,
            api_host: "https://cephalon.cloud/user-center/v1/model",
            group: ProviderGroup::Aggregator,
            sort_order: 43,
            api_version: None,
        },
        SystemProviderDef {
            id: "lanyun",
            name: "蓝云 (Lanyun)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://maas-api.lanyun.net",
            group: ProviderGroup::Aggregator,
            sort_order: 44,
            api_version: None,
        },
        SystemProviderDef {
            id: "ph8",
            name: "PH8",
            provider_type: ApiProviderType::Openai,
            api_host: "https://ph8.co",
            group: ProviderGroup::Aggregator,
            sort_order: 45,
            api_version: None,
        },
        SystemProviderDef {
            id: "sophnet",
            name: "SophNet",
            provider_type: ApiProviderType::Openai,
            api_host: "https://www.sophnet.com/api/open-apis/v1",
            group: ProviderGroup::Aggregator,
            sort_order: 46,
            api_version: None,
        },
        SystemProviderDef {
            id: "ocoolai",
            name: "ocoolAI",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.ocoolai.com",
            group: ProviderGroup::Aggregator,
            sort_order: 47,
            api_version: None,
        },
        SystemProviderDef {
            id: "dmxapi",
            name: "DMXAPI",
            provider_type: ApiProviderType::Openai,
            api_host: "https://www.dmxapi.cn",
            group: ProviderGroup::Aggregator,
            sort_order: 48,
            api_version: None,
        },
        SystemProviderDef {
            id: "aionly",
            name: "AIOnly",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.aiionly.com",
            group: ProviderGroup::Aggregator,
            sort_order: 49,
            api_version: None,
        },
        SystemProviderDef {
            id: "burncloud",
            name: "BurnCloud",
            provider_type: ApiProviderType::Openai,
            api_host: "https://ai.burncloud.com",
            group: ProviderGroup::Aggregator,
            sort_order: 50,
            api_version: None,
        },
        SystemProviderDef {
            id: "alayanew",
            name: "AlayaNew",
            provider_type: ApiProviderType::Openai,
            api_host: "https://deepseek.alayanew.com",
            group: ProviderGroup::Aggregator,
            sort_order: 51,
            api_version: None,
        },
        SystemProviderDef {
            id: "longcat",
            name: "LongCat",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.longcat.chat/openai",
            group: ProviderGroup::Aggregator,
            sort_order: 52,
            api_version: None,
        },
        SystemProviderDef {
            id: "poe",
            name: "Poe",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.poe.com/v1/",
            group: ProviderGroup::Aggregator,
            sort_order: 53,
            api_version: None,
        },
        SystemProviderDef {
            id: "huggingface",
            name: "Hugging Face",
            provider_type: ApiProviderType::OpenaiResponse,
            api_host: "https://router.huggingface.co/v1/",
            group: ProviderGroup::Aggregator,
            sort_order: 54,
            api_version: None,
        },
        SystemProviderDef {
            id: "vercel-gateway",
            name: "Vercel AI Gateway",
            provider_type: ApiProviderType::Gateway,
            api_host: "https://ai-gateway.vercel.sh/v1/ai",
            group: ProviderGroup::Aggregator,
            sort_order: 55,
            api_version: None,
        },
        // =========================================================================
        // 本地/自托管服务 (5个) - Requirements 3.5
        // =========================================================================
        SystemProviderDef {
            id: "ollama",
            name: "Ollama",
            provider_type: ApiProviderType::Ollama,
            api_host: "http://localhost:11434",
            group: ProviderGroup::Local,
            sort_order: 56,
            api_version: None,
        },
        SystemProviderDef {
            id: "lmstudio",
            name: "LM Studio",
            provider_type: ApiProviderType::Openai,
            api_host: "http://localhost:1234",
            group: ProviderGroup::Local,
            sort_order: 57,
            api_version: None,
        },
        SystemProviderDef {
            id: "new-api",
            name: "New API",
            provider_type: ApiProviderType::NewApi,
            api_host: "http://localhost:3000",
            group: ProviderGroup::Local,
            sort_order: 58,
            api_version: None,
        },
        SystemProviderDef {
            id: "gpustack",
            name: "GPUStack",
            provider_type: ApiProviderType::Openai,
            api_host: "",
            group: ProviderGroup::Local,
            sort_order: 59,
            api_version: None,
        },
        SystemProviderDef {
            id: "ovms",
            name: "OpenVINO Model Server",
            provider_type: ApiProviderType::Openai,
            api_host: "http://localhost:8000/v3/",
            group: ProviderGroup::Local,
            sort_order: 60,
            api_version: None,
        },
        // =========================================================================
        // 专用服务 (3个) - Requirements 3.6
        // =========================================================================
        SystemProviderDef {
            id: "jina",
            name: "Jina (Embedding/Rerank)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.jina.ai",
            group: ProviderGroup::Specialized,
            sort_order: 61,
            api_version: None,
        },
        SystemProviderDef {
            id: "voyageai",
            name: "VoyageAI (Embedding)",
            provider_type: ApiProviderType::Openai,
            api_host: "https://api.voyageai.com",
            group: ProviderGroup::Specialized,
            sort_order: 62,
            api_version: None,
        },
        SystemProviderDef {
            id: "cherryin",
            name: "CherryIN",
            provider_type: ApiProviderType::Openai,
            api_host: "https://open.cherryin.net",
            group: ProviderGroup::Specialized,
            sort_order: 63,
            api_version: None,
        },
    ]
}

/// 将 SystemProviderDef 转换为 ApiKeyProvider
pub fn to_api_key_provider(def: &SystemProviderDef) -> ApiKeyProvider {
    let now = Utc::now();
    ApiKeyProvider {
        id: def.id.to_string(),
        name: def.name.to_string(),
        provider_type: def.provider_type,
        api_host: def.api_host.to_string(),
        is_system: true,
        group: def.group,
        enabled: false,
        sort_order: def.sort_order,
        api_version: def.api_version.map(|s| s.to_string()),
        project: None,
        location: None,
        region: None,
        custom_models: Vec::new(),
        created_at: now,
        updated_at: now,
    }
}
